packages:
  - apps/*
  - packages/*
allowBuilds:
  "@prisma/client": true
  better-sqlite3: true
  esbuild: true
  msw: true
  sharp: true
  workerd: true
catalog:
  dotenv: ^17.4.2
  zod: ^4.4.3
  typescript: ^6.0.3
  "@types/node": 24.12.3
  "@cloudflare/workers-types": ^4.20260617.1
  hono: ^4.12.21
  "@orpc/server": ^1.14.2
  "@orpc/openapi": ^1.14.2
  "@orpc/zod": ^1.14.2
  better-auth: 1.6.11
  alchemy: ^0.93.9
  "@orpc/client": ^1.14.2
